set(['secondly', 'all', 'consider', 'whoever', 'results', 'four', 'edu', 'go', 'mill', 'evermore', 'causes', 'seemed', 'rd', 'certainly', 
	'biol', 'system', "when's", 'tweet', 'vs', 'ts', 'thursday', 'to', 'asking', 'present', 'th', 'under', 'sorry', 'promptly', "a's", 'mug', 
	'sent', '7', 'outside', 'far', 'mg', 'every', 'yourselves', 'fifty', "we'll", 'went', 'did', 'forth', "they've", 'fewer', 'try', 'p', 
	'thereupon', 'round', 'added', "it'll", "i'll", 'someday', 'approximately', 'says', "you'd", 'ten', 'yourself', 'd', 'past', 'reuters', 
	'likely', 'invention', 'notwithstanding', 'further', 'even', 'index', 'what', 'appear', 'giving', 'sun', 'section', 'brief', 'run', 
	'goes', 'sup', 'new', 'poorly', 'ever', 'thin', 'full', "c'mon", 'whose', 'youd', 'respectively', 'sincere', 'never', 'here', 
	'himself', 'let', 'others', "hadn't", 'along', "aren't", 'shows', 'suggest', 'obtained', 'ref', 'ahead', 'k', 'allows', 
	'proud', 'amount', "i'd", 'resulting', 'howbeit', 'usually', 'whereupon', "i'm", 'makes', 'thats', 'hither', 'via', 'followed', 
	'merely', 'while', 'homepage', 'till', 'ninety', 'vols', 'viz', 'ord', 'readily', 'everybody', 'use', 'from', 'would', '0', 'contains', 
	'two', 'next', 'few', 'call', 'therefore', '6', 'taken', 'themselves', 'thru', 'tell', 'more', 'knows', 'becomes', 'hereby', 'yahoo', 
	'herein', "ain't", '8', 'particular', 'known', "who'll", 'bill', 'must', 'me', 'none', 'include', 'thanks', 'f', 'this', 'ml', 'oh', 
	'anywhere', 'nine', 'can', 'mr', 'following', 'thickv', 'my', 'example', 'saturday', 'indicated', 'give', 'december', 'neverf', "didn't", 
	'states', 'indicates', 'something', 'want', 'arise', 'stories', 'story', 'needs', 'end', 'thing', 'rather', 'newsinfo', 'meanwhile', 
	'ng', '1', 'how', 'sunday', 'low', "'ve", 'instead', 'de', 'okay', 'tried', 'may', 'stop', 'after', 'eighty', 'different', 'hereupon', 
	'whilst', 'ff', 'date', 'such', 'undoing', 'a', 'thered', 'third', 'whenever', 'maybe', 'appreciate', 'q', ')', 'ones', 'so', 
	'specifying', 'allow', 'keeps', 'sa', 'sat', "that's", 'thirty', 'six', 'help', "don't", 'september', 'indeed', 'over', 'move', 
	'mainly', 'soon', 'years', 'course', 'through', 'looks', 'fify', 'still', 'its', 'refs', 'before', 'police', 'thank', "he's", 'selves', 
	'inward', 'fix', ',', 'actually', 'better', 'whether', 'willing', 'whole', 'thanx', 'ours', 'might', "haven't", '2012', 'versus', 
	'then', 'non', 'someone', 'somebody', 'thereby', '3', 'auth', 'underneath', "you've", 'they', 'half', 'not', 'now', 'nor', 'nos', 
	'february', 'several', 'hereafter', 'always', 'reasonably', 'whither', "she's", 'sufficiently', 'each', 'found', 'entirely', 'yung', 
	"mustn't", "isn't", 'mean', 'everyone', 'directly', 'doing', 'ed', 'eg', 'related', 'wednesday', 'owing', 'fifteen', 'ex', 'year', 
	'substantially', 'et', 'beyond', 'couldnt', 'out', 'by', 'them', "needn't", 'furthermore', 'since', 'forty', 'research', 'looking', 
	're', 'seriously', "shouldn't", "they'll", 'inquirer', 'got', 'cause', "one's", "you're", 'amoungst', 'million', 'given', 'quite', 
	"what'll", 'que', 'besides', 'x', 'ask', 'anyhow', 'beginning', 'backwards', 'g', 'could', 'similarly', 'put', 'tries', 'keep', 
	'caption', 'w', 'ltd', 'hence', 'onto', 'think', 'first', 'myself', 'already', 'seeming', 'omitted', 'thereafter', 'thereof', 
	'awfully', 'done', 'adopted', 'another', 'thick', 'miss', "doesn't", 'little', 'necessarily', 'their', 'together', 'top', 'accordingly', 
	'least', 'name', 'anyone', 'indicate', '2', 'too', 'hundred', 'gives', 'herself', 'mostly', 'that', 'nobody', 'took', 
	'immediate', 'resulted', 'regards', 'somewhat', 'off', 'july', 'believe', 'herself', 'than', "here's", 'begins', '10', 'b', 
	'unfortunately', 'showed', 'accordance', 'gotten', 'second', 'i', 'r', 'amid', 'toward', 'minus', 'are', 'and', 'youre', 'ran', 
	'thoughh', 'alongside', 'beforehand', 'mine', 'say', 'unlikely', 'have', 'need', 'seen', 'seem', 'saw', 'any', 'relatively', 'rappler', 
	'zero', 'thoroughly', 'latter', 'downwards', 'aside', 'thorough', 'predominantly', 'also', 'take', 'which', 'begin', 'exactly', 'unless', 
	'opposite', 'who', "where's", 'most', 'eight', 'but', 'significant', 'nothing', 'why', 'sub', 'forever', 'kg', 'especially', 'yun', 
	'noone', 'later', 'm', 'km', 'mrs', 'heres', "you'll", 'definitely', 'neverless', 'normally', 'came', 'saying', 'particularly', ' ', 
	'show', 'able', 'anyway', 'ending', "that'll", 'find', 'fifth', 'one', 'specifically', "daren't", '(', 'behind', "won't", 'should', 
	'only', 'going', 'specify', 'photo', 'announce', 'itd', "there've", 'do', 'his', 'above', 'get', 'between', 'overall', 'ko', 'truly', 
	"they'd", "oughtn't", 'cannot', 'hid', 'nearly', 'words', 'despite', 'during', 'him', 'regarding', 'qv', 'h', 'cry', "mayn't", 'state', 
	'twice', 'she', 'though', 'contain', "what've", 'where', 'greetings', 'ignored', 'theirs', 'eleven', 'up', 'namely', 'computer', 'sec', 
	'anyways', "that've", 'throug', 'no-one', 'best', 'wonder', 'said', "there'd", 'away', 'currently', 'please', 'ups', 'enough', "there's", 
	'various', 'hopefully', 'affecting', 'probably', 'neither', 'across', 'co.', 'available', 'we', 'recently', 'august', 'useful', 
	'importance', 'were', 'however', 'news', 'meantime', 'come', 'tue', 'both', 'c', 'last', 'thou', 'many', 'taking', 'thence', 'according', 
	'against', 'etc', 's', 'became', 'rapplercom', 'com', "can't", 'otherwise', 'among', 'liked', 'co', 'afterwards', 'seems', 'ca', 
	'whatever', 'alone', 'ang', "couldn't", 'moreover', 'throughout', 'november', 'considering', "he'd", 'pp', 'described', 
	'\xef\xbb\xbfable', "it's", 'fri', 'three', 'been', 'quickly', 'whom', "there're", 'much', 'wherein', 'interest', 'certain', 'whod', 
	'hardly', "it'd", 'pm', 'wants', 'corresponding', 'fire', 'latterly', 'concerning', '-', 'else', 'hers', 'former', 'those', 'myself', 
	'novel', 'look', 'unlike', 'twenty', 'these', 'means', 'tip', 'thereto', 'value', 'n', 'will', 'near', '2013', "wouldn't", 'theres', 
	'seven', 'whereafter', 'almost', 'wherever', 'is', 'thus', 'it', 'cant', 'itself', 'im', 'in', 'affected', 'ie', 'id', 'if', 
	'containing', 'anymore', 'april', 'perhaps', 'insofar', 'make', 'same', 'clearly', 'beside', 'potentially', 'widely', '9', 'ako', 
	'gets', "weren't", 'fairly', 'used', 'y', 'slightly', 'see', 'somewhere', 'keys', 'upon', 'effect', 'uses', 'yours', "he'll", 'wheres', 
	'recent', 'lower', 'kept', 'whereby', 'largely', 'nevertheless', 'changes', 'thu', 'nonetheless', 'well', 'anybody', 'obviously', 
	'without', 'comes', 'very', 'the', 'con', 'self', 'inc.', 'mon', 'lest', 'things', 'world', "she'll", 'just', 'less', 'being', 'when', 
	'therere', 'presumably', 'front', 'farther', 'immediately', 'regardless', 'yes', 'october', 'yet', 'unto', 'wed', "we've", 'percent', 
	'had', 'except', 'thousand', 'lets', '4', 'monday', 'has', 'adj', 'tuesday', 'ought', 'gave', "t's", 'arent', 'march', 'around', 
	'government', "who's", 'possible', 'usefully', 'possibly', 'whichever', 'five', 'know', 'using', 'part', "who'd", 'dare', 'apart', 
	'abst', 'nay', 'necessary', 'like', 'follows', 'noted', 'either', 'january', 'become', 'whomever', 'towards', 'therein', "why's", 
	'www', 'because', 'old', 'often', 'people', 'successfully', 'some', 'back', 'l', 'ah', 'sure', 'shes', 'specified', 'home', 'theyre', 
	'ourselves', "shan't", 'happens', 'provided', 'vol', "there'll", 'for', 'bottom', 'affects', 'shall', 'per', 'everything', 'does', 
	'provides', 'tends', 't', 'be', "mightn't", 'sensible', 'obtain', 'sports', 'nowhere', 'although', 'sixty', 'abroad', 'on', 'about', 
	'ok', 'anything', 'getting', 'of', 'v', 'o', 'page', 'whence', 'plus', 'act', 'consequently', 'or', 'seeing', 'own', 'whats', 
	'formerly', 'twelve', 'previously', 'somethan', 'into', 'within', 'shed', 'due', 'down', 'appropriate', 'right', 'primarily', 'theyd', 
	'side', "c's", 'whos', 'your', 'significantly', 'fill', "how's", 'her', 'hes', 'aren', 'apparently', 'there', 'amidst', 'pages', 'hed', 
	'inasmuch', 'inner', 'way', 'forward', ':', 'was', 'himself', 'elsewhere', "i've", 'becoming', 'amongst', 'somehow', 'hi', 'et-al', 
	'line', 'trying', 'with', 'he', 'usefulness', "they're", 'made', 'friday', "wasn't", 'wish', 'inside', 'j', "hasn't", 'us', 'until', 
	'placed', 'below', 'un', 'whim', 'empty', '.', 'z', 'similar', "we'd", 'strongly', 'gone', 'sometimes', 'associated', 'likewise', 
	'describe', 'am', 'itself', 'an', 'as', 'sometime', 'at', 'our', 'inc', 'again', 'hasnt', "'ll", 'no', 'na', 'whereas', 'nd', 
	'detail', 'lately', 'til', 'other', '5', 'you', 'really', "what's", 'showns', 'briefly', 'beginnings', 'welcome', 'june', 'shown', 
	"let's", 'important', 'serious', '\xef\xbb\xbfI', 'upwards', 'ago', 'e', "she'd", 'having', '\xef\xbb\xbfa', 'u', "we're", 'time', 
	'everywhere', 'backward', 'hello', 'once'])
